### ISSUE TITLE
Take care with aws-sdk response

### ISSUE THREAD

**Issue by JordiSapesPlanas** [oriolagobat/Practica-CDA#1]
https://github.com/oriolagobat/Practica-CDA/blob/27f8481787cb5926ee39a4e91cb5586ac17e837a/practices/practice2/get.ts#L4

Hola Oriol! Aqui has modificat el Promise<void> per Promisie<GetItemOutput>. Per aquesta practica no feia falta. Ves amb cuidado amb la definicio de getItemOutput. Perque la resposta a més a més de tornar el Item que insertes a la BBDD et retorna mes informació. Per tant nomes necessites obtenir de la resposta el paramter Item.

**Comment by oriolagobat** [comment]
He estat mirant, he fet que retorni la part _Item_ del resultat, modificant també el _output_ de la funció per a que sigui:
`Promise<DocumentClient.AttributeMap | undefined>`.
Isue closed
